server:
  port: 7777
logging:
  level:
    org:
      springframework.security: DEBUG
    com:
      sharekh: DEBUG
spring:
  datasource:
    username: postgres
    password: 1
    url: jdbc:postgresql://localhost:5432/isharekh
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true